export const typeColors = [
    { type: "bug", code: "#8CB230" },
    { type: "dark", code: "#58575F" },
    { type: "dragon", code: "#0F6AC0" },
    { type: "electric", code: "#eab308" },
    { type: "fairy", code: "#ED6EC7" },
    { type: "fighting", code: "#D04164" },
    { type: "fire", code: "#FD7D24" },
    { type: "flying", code: "#748FC9" },
    { type: "ghost", code: "#556AAE" },
    { type: "grass", code: "#62B957" },
    { type: "ground", code: "#DD7748" },
    { type: "normal", code: "#9DA0AA" },
    { type: "poison", code: "#A552CC" },
    { type: "ice", code: "#61CECO" },
    { type: "psychic", code: "#EA5D60" },
    { type: "rock", code: "#BAAB82" },
    { type: "steel", code: "#417D9A" },
    { type: "water", code: "#4A90DA" },
  ];
